import type { Note } from "./types";

export const mockNotes: Note[] = [
  {
    id: "n-01",
    title: "Redis vs Memcached for Session Caching",
    content: `Been evaluating both for the session layer. Redis wins on feature set — persistence, pub/sub, data structures — but Memcached is simpler and faster for pure key-value. For our use case (session tokens + short-lived cache), Redis Cluster with 30s TTL seems right. Need to benchmark eviction under load.\n\nKey considerations:\n- Redis supports hash types which map cleanly to session objects\n- Memcached has better multi-threaded performance for simple gets\n- Redis Sentinel vs Cluster for HA — Cluster is more complex but handles partitioning\n- Memory fragmentation is worse in Redis for small values\n\nNext step: run latency benchmarks with realistic payload sizes (2-8KB session blobs).`,
    summary:
      "Comparison of Redis vs Memcached for session caching with focus on eviction policies, data structures, and high-availability clustering.",
    tags: ["redis", "architecture", "infrastructure", "performance"],
    updatedAt: "2026-03-19T22:14:00Z",
    createdAt: "2026-03-17T09:30:00Z",
    imageCount: 0,
    wordCount: 142,
    status: "organized",
    isPinned: true,
  },
  {
    id: "n-02",
    title: "Auth Token Refresh Flow — Edge Cases",
    content: `The refresh token rotation is mostly working but I found two edge cases:\n\n1. When the access token expires during a server action, the middleware refresh races with the action itself. Fix: queue server actions behind a token-check gate.\n\n2. If the user has two tabs open and both trigger refresh simultaneously, the second one gets a 401 because the first rotation invalidated the old refresh token. Fix: implement a short grace period (5-10s) where the old refresh token is still accepted.\n\nAlso need to think about what happens when the refresh token itself expires. Current behavior is silent redirect to sign-in, which is correct but should show a toast.`,
    summary:
      "Edge cases in the auth token refresh rotation flow, particularly around race conditions with concurrent tabs and server actions.",
    tags: ["auth", "security", "typescript", "debugging"],
    updatedAt: "2026-03-19T18:45:00Z",
    createdAt: "2026-03-18T14:20:00Z",
    imageCount: 0,
    wordCount: 158,
    status: "organized",
  },
  {
    id: "n-03",
    title: "RAG Pipeline Architecture Notes",
    content: `Thinking through the retrieval pipeline for the semantic search feature.\n\nEmbedding model: text-embedding-3-small (1536 dims, good enough for note-length text)\nVector store: pgvector extension on existing Postgres\nChunking: probably not needed since notes are short-to-medium length. Embed the full content.\n\nRetrieval flow:\n1. User types query in Cmd+K\n2. Embed the query\n3. Cosine similarity search, top-k=10\n4. Re-rank with a lightweight cross-encoder or just trust cosine\n5. Return note metadata + snippet\n\nOpen question: should we embed title+content or just content? Title might anchor the embedding too much toward the label rather than the substance.`,
    summary:
      "Architecture sketch for the semantic search RAG pipeline using pgvector, text-embedding-3-small, and cosine similarity retrieval.",
    tags: ["rag", "architecture", "ai", "search"],
    updatedAt: "2026-03-18T21:00:00Z",
    createdAt: "2026-03-15T10:00:00Z",
    imageCount: 0,
    wordCount: 145,
    status: "organized",
  },
  {
    id: "n-04",
    title: "Next.js App Router Caching Gotchas",
    content: `ran into a few things today that weren't obvious from the docs:\n\n- fetch() in server components is cached by default in production. Need to explicitly set { cache: 'no-store' } or use revalidate.\n- generateStaticParams + dynamic routes: if you return an empty array, the route becomes fully dynamic. Not always what you want.\n- Route handlers (GET) are cached at build time if they don't read request. This caught me off guard.\n- unstable_cache is actually stable now in Next 15+ but the name hasn't changed.\n\nThe mental model: everything is static until you opt into dynamism. Opposite of Pages Router.`,
    summary:
      "Gotchas with Next.js App Router caching defaults including fetch behavior, route handlers, and the static-by-default mental model.",
    tags: ["nextjs", "performance", "typescript"],
    updatedAt: "2026-03-18T16:30:00Z",
    createdAt: "2026-03-18T15:00:00Z",
    imageCount: 0,
    wordCount: 128,
    status: "organized",
  },
  {
    id: "n-05",
    title: "Observability Stack Decision",
    content: `Need to pick an observability setup before we start scaling. Options on the table:\n\n1. Datadog — full platform, expensive, great DX\n2. Grafana Cloud — cheaper, good for metrics + logs, Tempo for traces\n3. Self-hosted LGTM stack — maximum control, operational overhead\n\nFor a single-user product at this stage, Grafana Cloud free tier is probably fine. Can always upgrade. Key things to instrument first:\n- API response times (p50, p95, p99)\n- Error rates by route\n- Auth flow success/failure\n- AI endpoint latency\n\nShould also add structured logging from day one. Using pino with JSON output.`,
    summary:
      "Decision log for choosing an observability stack. Leaning toward Grafana Cloud free tier with pino structured logging.",
    tags: ["observability", "infrastructure", "devops"],
    updatedAt: "2026-03-17T14:20:00Z",
    createdAt: "2026-03-16T09:00:00Z",
    imageCount: 2,
    wordCount: 120,
    status: "organized",
  },
  {
    id: "n-06",
    title: "Untitled debugging session",
    content: `the thing where prisma throws P2002 on upsert when there's a race condition between two concurrent requests trying to create the same unique record. the "unique constraint failed" error.\n\nworkaround: wrap the upsert in a try/catch and retry once on P2002. or use a transaction with serializable isolation. the retry is simpler.\n\nalso seeing this in the tag creation flow when two notes get the same new tag at the same time.`,
    summary: "",
    tags: ["debugging", "prisma"],
    updatedAt: "2026-03-17T11:05:00Z",
    createdAt: "2026-03-17T10:48:00Z",
    imageCount: 0,
    wordCount: 82,
    status: "draft",
  },
  {
    id: "n-07",
    title: "TypeScript Strict Mode Migration Checklist",
    content: `Checklist for turning on strict mode in tsconfig without breaking everything:\n\n- [x] Enable strictNullChecks first (biggest impact)\n- [x] Fix all "possibly undefined" errors\n- [ ] Enable noImplicitAny\n- [ ] Fix all implicit any types (mostly event handlers and API responses)\n- [ ] Enable strictFunctionTypes\n- [ ] Enable strictBindCallApply\n- [ ] Enable strictPropertyInitialization (class-heavy code only)\n- [ ] Final: set "strict": true and remove individual flags\n\nDoing this incrementally is way better than flipping the switch. Each flag adds ~20-50 errors in a medium codebase.`,
    summary:
      "Step-by-step checklist for migrating a TypeScript project to strict mode incrementally to avoid overwhelming error counts.",
    tags: ["typescript", "devops", "migration"],
    updatedAt: "2026-03-16T19:00:00Z",
    createdAt: "2026-03-14T08:00:00Z",
    imageCount: 0,
    wordCount: 110,
    status: "organized",
  },
  {
    id: "n-08",
    title: "quick thought on embeddings",
    content: `what if we stored both a title embedding and a content embedding separately, then weighted them at query time? title embedding would catch "find my redis notes" while content embedding catches "that thing about eviction policies".\n\ncould even let the user toggle between "search titles" and "search content" in the palette. or just concatenate with a separator and embed once.`,
    summary: "",
    tags: ["ai", "search", "rag"],
    updatedAt: "2026-03-16T08:30:00Z",
    createdAt: "2026-03-16T08:22:00Z",
    imageCount: 0,
    wordCount: 68,
    status: "draft",
  },
  {
    id: "n-09",
    title: "Deployment Pipeline Design",
    content: `Current deploy is manual: push to main, Vercel auto-deploys. That's fine for now but need to think about:\n\n1. Preview deployments for PRs — Vercel does this automatically\n2. Database migrations — need to run prisma migrate deploy before the new code goes live\n3. Environment variable management — using Vercel env vars, but should have a .env.example\n4. Rollback strategy — Vercel instant rollback is great, but DB migrations aren't reversible by default\n\nFor the migration timing problem: run migrations in a GitHub Action before the Vercel deploy webhook triggers. Or use prisma migrate with a pre-deploy script.`,
    summary:
      "Design considerations for the deployment pipeline including migration timing, preview deploys, and rollback strategy with Vercel.",
    tags: ["devops", "infrastructure", "prisma"],
    updatedAt: "2026-03-15T20:00:00Z",
    createdAt: "2026-03-13T11:00:00Z",
    imageCount: 1,
    wordCount: 122,
    status: "organized",
  },
  {
    id: "n-10",
    title: "Image Upload Validation Rules",
    content: `Need to define validation for note image uploads:\n\n- Max file size: 5MB per image\n- Accepted types: image/jpeg, image/png, image/webp, image/gif\n- Max images per note: 10\n- Client-side validation before upload\n- Server-side validation as second check\n- Store in InsForge storage bucket with note_id prefix\n\nUI considerations:\n- Drag and drop zone in the editor\n- Thumbnail preview grid below the content\n- Remove button on each thumbnail\n- Upload progress indicator\n- Error state for rejected files (too large, wrong type)`,
    summary:
      "Specification for note image upload validation including file size limits, accepted types, and UI considerations for the editor.",
    tags: ["architecture", "storage", "ux"],
    updatedAt: "2026-03-15T14:00:00Z",
    createdAt: "2026-03-15T13:30:00Z",
    imageCount: 3,
    wordCount: 98,
    status: "organized",
  },
  {
    id: "n-11",
    title: "perf issue with large note lists",
    content: `noticed the note list gets sluggish around 200+ items when filtering. the filter runs on every keystroke and re-renders the entire list.\n\nfix options:\n1. debounce the search input (easy, 200ms delay)\n2. virtualize the list with react-window or tanstack virtual\n3. useDeferredValue for the search query\n4. move filtering to a web worker (overkill for now)\n\nprobably start with debounce + useDeferredValue. virtualization can wait until we actually have users with 200+ notes.`,
    summary: "",
    tags: ["performance", "react", "debugging"],
    updatedAt: "2026-03-14T17:00:00Z",
    createdAt: "2026-03-14T16:40:00Z",
    imageCount: 0,
    wordCount: 84,
    status: "draft",
  },
  {
    id: "n-12",
    title: "Tailwind v4 Migration Notes",
    content: `Migrated from Tailwind v3 to v4. Key differences:\n\n- No more tailwind.config.js — everything in CSS with @theme\n- @apply still works but discouraged for new code\n- Content detection is automatic, no content array needed\n- Custom variants use @custom-variant instead of plugins\n- Colors use oklch by default (better perceptual uniformity)\n- New @theme inline block for exposing design tokens\n\nThe migration was mostly smooth. Biggest issue was custom plugins — had to rewrite them as CSS custom properties. Also the JIT mode is just how it works now, no opt-in needed.`,
    summary:
      "Notes from migrating Tailwind CSS v3 to v4 covering configuration changes, custom variants, oklch colors, and plugin rewrites.",
    tags: ["css", "tailwind", "migration"],
    updatedAt: "2026-03-13T15:00:00Z",
    createdAt: "2026-03-12T09:00:00Z",
    imageCount: 0,
    wordCount: 112,
    status: "organized",
  },
  {
    id: "n-13",
    title: "API Rate Limiting Strategy",
    content: `Need rate limiting on the AI endpoints to prevent abuse and control costs.\n\nApproach:\n- Token bucket algorithm per user\n- Limits: 20 requests/minute for auto-organize, 60 requests/minute for search\n- Store counters in Redis (or in-memory Map for dev)\n- Return 429 with Retry-After header\n- Client should show a gentle "slow down" message, not a hard error\n\nImplementation: middleware-level check before hitting the AI service. Can use upstash/ratelimit for serverless-friendly implementation.\n\nEdge case: what about the debounced autosave? That's not AI but hits the API frequently. Should have its own higher limit (120/min).`,
    summary:
      "Rate limiting strategy for AI endpoints using token bucket per user, with separate limits for auto-organize, search, and autosave.",
    tags: ["api", "security", "infrastructure", "ai"],
    updatedAt: "2026-03-12T18:00:00Z",
    createdAt: "2026-03-11T14:00:00Z",
    imageCount: 0,
    wordCount: 118,
    status: "organized",
  },
  {
    id: "n-14",
    title: "random thought about tag UX",
    content: `tags should autocomplete from existing tags when typing. don't want users creating "typescript", "Typescript", "TS", and "ts" as four separate tags.\n\nnormalization: lowercase, trim, collapse whitespace. maybe even suggest merges if two tags are very similar (levenshtein distance < 2).\n\nalso: should tags be free-form or from a predefined set? free-form is more flexible but gets messy. predefined is cleaner but limiting. maybe free-form with AI suggestions from existing tags?`,
    summary: "",
    tags: ["ux", "architecture"],
    updatedAt: "2026-03-11T09:15:00Z",
    createdAt: "2026-03-11T09:10:00Z",
    imageCount: 0,
    wordCount: 76,
    status: "draft",
  },
];
